name: microsoft.todo

networks:
  default:
    name: microsoft.todo

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}
    ports:
      - "1433:1433"
  
  api:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: microsoft.todo-api
    image: microsoft.todo-api:latest
    ports:
      - '7777:7777'
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      FrontendOptions__BaseUrl: http://localhost:4200
      ConnectionStrings__MsSql: ${MSSQL_CONNECTION_STRING}
      JwtOptions__Issuer: ${JWT_TOKEN_ISSUER}
      JwtOptions__Audience: ${JWT_TOKEN_AUDIENCE}
      JwtOptions__SecretKey: ${JWT_TOKEN_SECRET_KEY}
      JwtOptions__ExpirationHours: ${JWT_TOKEN_EXPIRATION_HOURS}
    depends_on:
      - mssql
  
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: microsoft.todo-frontend
    image: microsoft.todo-frontend:latest
    ports:
      - '4200:80'
    depends_on:
      - api